[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "endstone-blockdata-inspector"
version = "0.4.5b30"
description = "In-game container, NBT, and block state inspection test plugin for Endstone"
readme = "README.md"
requires-python = "==3.14.*"
dependencies = [
    "endstone==0.11.6",
]

[project.entry-points."endstone"]
"blockdata-inspector" = "endstone_blockdata_inspector:BlockDataInspectorPlugin"

[tool.setuptools]
packages = ["endstone_blockdata_inspector"]
package-dir = {"" = "src"}
